// n = nazwa PL, c = stolica PL, e = nazwa(y) obiektu na mapie (Natural Earth),
// an = alternatywne nazwy państwa, ac = alternatywne nazwy stolicy, p = punkt [lon, lat] gdy brak obrysu
window.CONTINENTS = {
  europa: {
    label: 'Europa',
    rotate: [-15, -52],
    fitPoints: [[-24, 35], [50, 35], [-24, 71], [50, 71], [30, 72]],
    countries: [
      { n: 'Albania', c: 'Tirana', e: 'Albania' },
      { n: 'Andora', c: 'Andora', e: 'Andorra', an: ['Andorra'], ac: ['Andora la Vella', 'Andorra la Vella'] },
      { n: 'Austria', c: 'Wiedeń', e: 'Austria', ac: ['Wien', 'Vienna'] },
      { n: 'Belgia', c: 'Bruksela', e: 'Belgium', ac: ['Brussels'] },
      { n: 'Białoruś', c: 'Mińsk', e: 'Belarus' },
      { n: 'Bośnia i Hercegowina', c: 'Sarajewo', e: 'Bosnia and Herz.', an: ['Bośnia', 'BiH'], ac: ['Sarajevo'] },
      { n: 'Bułgaria', c: 'Sofia' , e: 'Bulgaria' },
      { n: 'Chorwacja', c: 'Zagrzeb', e: 'Croatia', ac: ['Zagreb'] },
      { n: 'Czarnogóra', c: 'Podgorica', e: 'Montenegro' },
      { n: 'Czechy', c: 'Praga', e: 'Czechia', an: ['Czechia', 'Republika Czeska'] },
      { n: 'Dania', c: 'Kopenhaga', e: 'Denmark' },
      { n: 'Estonia', c: 'Tallinn', e: 'Estonia', ac: ['Tallin'] },
      { n: 'Finlandia', c: 'Helsinki', e: 'Finland' },
      { n: 'Francja', c: 'Paryż', e: 'France' },
      { n: 'Grecja', c: 'Ateny', e: 'Greece' },
      { n: 'Hiszpania', c: 'Madryt', e: 'Spain', ac: ['Madrid'] },
      { n: 'Holandia', c: 'Amsterdam', e: 'Netherlands', an: ['Niderlandy'] },
      { n: 'Irlandia', c: 'Dublin', e: 'Ireland' },
      { n: 'Islandia', c: 'Reykjavík', e: 'Iceland', ac: ['Rejkiawik'] },
      { n: 'Kosowo', c: 'Prisztina', e: 'Kosovo', ac: ['Pristina', 'Prishtina'] },
      { n: 'Liechtenstein', c: 'Vaduz', e: 'Liechtenstein', an: ['Lichtenstein'] },
      { n: 'Litwa', c: 'Wilno', e: 'Lithuania', ac: ['Vilnius'] },
      { n: 'Luksemburg', c: 'Luksemburg', e: 'Luxembourg', an: ['Luxembourg'], ac: ['Luxembourg'] },
      { n: 'Łotwa', c: 'Ryga', e: 'Latvia', ac: ['Riga'] },
      { n: 'Macedonia Północna', c: 'Skopje', e: 'Macedonia', an: ['Macedonia'] },
      { n: 'Malta', c: 'Valletta', e: 'Malta', ac: ['La Valletta', 'Valetta'] },
      { n: 'Mołdawia', c: 'Kiszyniów', e: 'Moldova', an: ['Mołdowa'], ac: ['Kiszyniow', 'Chisinau'] },
      { n: 'Monako', c: 'Monako', e: 'Monaco', an: ['Monaco'], ac: ['Monaco'] },
      { n: 'Niemcy', c: 'Berlin', e: 'Germany' },
      { n: 'Norwegia', c: 'Oslo', e: 'Norway' },
      { n: 'Polska', c: 'Warszawa', e: 'Poland' },
      { n: 'Portugalia', c: 'Lizbona', e: 'Portugal', ac: ['Lisbona'] },
      { n: 'Rosja', c: 'Moskwa', e: 'Russia', an: ['Federacja Rosyjska'] },
      { n: 'Rumunia', c: 'Bukareszt', e: 'Romania' },
      { n: 'San Marino', c: 'San Marino', e: 'San Marino' },
      { n: 'Serbia', c: 'Belgrad', e: 'Serbia' },
      { n: 'Słowacja', c: 'Bratysława', e: 'Slovakia' },
      { n: 'Słowenia', c: 'Lublana', e: 'Slovenia', ac: ['Ljubljana'] },
      { n: 'Szwajcaria', c: 'Berno', e: 'Switzerland', ac: ['Bern'] },
      { n: 'Szwecja', c: 'Sztokholm', e: 'Sweden' },
      { n: 'Ukraina', c: 'Kijów', e: 'Ukraine' },
      { n: 'Węgry', c: 'Budapeszt', e: 'Hungary' },
      { n: 'Watykan', c: 'Watykan', e: 'Vatican', ac: ['Vatican City'] },
      { n: 'Wielka Brytania', c: 'Londyn', e: 'United Kingdom', an: ['Zjednoczone Królestwo', 'UK'] },
      { n: 'Włochy', c: 'Rzym', e: 'Italy' }
    ]
  },

  afryka: {
    label: 'Afryka',
    rotate: [-17, -2],
    countries: [
      { n: 'Algieria', c: 'Algier', e: 'Algeria' },
      { n: 'Egipt', c: 'Kair', e: 'Egypt', ac: ['Kairo'] },
      { n: 'Erytrea', c: 'Asmara', e: 'Eritrea' },
      { n: 'Etiopia', c: 'Addis Abeba', e: 'Ethiopia', ac: ['Addis Ababa'] },
      { n: 'Gabon', c: 'Libreville', e: 'Gabon' },
      { n: 'Gambia', c: 'Bandżul', e: 'Gambia', ac: ['Banjul'] },
      { n: 'Ghana', c: 'Akra', e: 'Ghana', ac: ['Accra'] },
      { n: 'Kamerun', c: 'Jaunde', e: 'Cameroon', ac: ['Yaounde'] },
      { n: 'Kenia', c: 'Nairobi', e: 'Kenya' },
      { n: 'Kongo', c: 'Brazzaville', e: 'Congo', an: ['Republika Konga'] },
      { n: 'Liberia', c: 'Monrovia', e: 'Liberia' },
      { n: 'Libia', c: 'Trypolis', e: 'Libya', ac: ['Trypoli', 'Tripoli'] },
      { n: 'Madagaskar', c: 'Antananarywa', e: 'Madagascar', ac: ['Antananarivo'] },
      { n: 'Malawi', c: 'Lilongwe', e: 'Malawi' },
      { n: 'Mali', c: 'Bamako', e: 'Mali' },
      { n: 'Maroko', c: 'Rabat', e: 'Morocco' },
      { n: 'Mauretania', c: 'Nawakszut', e: 'Mauritania', ac: ['Nouakchott'] },
      { n: 'Mozambik', c: 'Maputo', e: 'Mozambique' },
      { n: 'Namibia', c: 'Windhuk', e: 'Namibia', ac: ['Windhoek'] },
      { n: 'Niger', c: 'Niamey', e: 'Niger', ac: ['Niamej'] },
      { n: 'Nigeria', c: 'Abudża', e: 'Nigeria', ac: ['Abuja'] },
      { n: 'Rwanda', c: 'Kigali', e: 'Rwanda' },
      { n: 'Senegal', c: 'Dakar', e: 'Senegal' },
      { n: 'Seszele', c: 'Victoria', e: 'Seychelles', ac: ['Wiktoria'] },
      { n: 'Somalia', c: 'Mogadiszu', e: ['Somalia', 'Somaliland'], ac: ['Mogadishu'] },
      { n: 'Sudan', c: 'Chartum', e: 'Sudan', ac: ['Khartoum'] },
      { n: 'Sudan Południowy', c: 'Dżuba', e: 'S. Sudan', ac: ['Juba'] },
      { n: 'Tanzania', c: 'Dodoma', e: 'Tanzania' },
      { n: 'Togo', c: 'Lomé', e: 'Togo' },
      { n: 'Tunezja', c: 'Tunis', e: 'Tunisia' },
      { n: 'Uganda', c: 'Kampala', e: 'Uganda' },
      { n: 'Zambia', c: 'Lusaka', e: 'Zambia' },
      { n: 'Zimbabwe', c: 'Harare', e: 'Zimbabwe' }
    ]
  },

  ameryka_pd: {
    label: 'Ameryka Południowa',
    rotate: [60, 20],
    countries: [
      { n: 'Argentyna', c: 'Buenos Aires', e: 'Argentina' },
      { n: 'Boliwia', c: 'Sucre', e: 'Bolivia' },
      { n: 'Brazylia', c: 'Brasília', e: 'Brazil' },
      { n: 'Chile', c: 'Santiago de Chile', e: 'Chile', ac: ['Santiago'] },
      { n: 'Ekwador', c: 'Quito', e: 'Ecuador', ac: ['Kito'] },
      { n: 'Kolumbia', c: 'Bogotá', e: 'Colombia' },
      { n: 'Paragwaj', c: 'Asunción', e: 'Paraguay' },
      { n: 'Peru', c: 'Lima', e: 'Peru' },
      { n: 'Urugwaj', c: 'Montevideo', e: 'Uruguay' },
      { n: 'Wenezuela', c: 'Caracas', e: 'Venezuela', ac: ['Karakas'] }
    ]
  },

  ameryka_pn: {
    label: 'Ameryka Północna',
    rotate: [95, -40],
    countries: [
      { n: 'Bahamy', c: 'Nassau', e: 'Bahamas' },
      { n: 'Dominikana', c: 'Santo Domingo', e: 'Dominican Rep.', an: ['Republika Dominikańska'] },
      { n: 'Grenada', c: "Saint George's", e: 'Grenada', ac: ["St. George's", 'Saint George'] },
      { n: 'Gwatemala', c: 'Gwatemala', e: 'Guatemala', ac: ['Guatemala', 'Gwatemala City'] },
      { n: 'Jamajka', c: 'Kingston', e: 'Jamaica' },
      { n: 'Kanada', c: 'Ottawa', e: 'Canada' },
      { n: 'Kostaryka', c: 'San José', e: 'Costa Rica', an: ['Costa Rica'] },
      { n: 'Kuba', c: 'Hawana', e: 'Cuba', ac: ['Havana'] },
      { n: 'Meksyk', c: 'Meksyk', e: 'Mexico', ac: ['Mexico City', 'Miasto Meksyk'] },
      { n: 'Panama', c: 'Panama', e: 'Panama', ac: ['Panama City'] },
      { n: 'Salwador', c: 'San Salvador', e: 'El Salvador', an: ['El Salvador'] },
      { n: 'Stany Zjednoczone', c: 'Waszyngton', e: 'United States of America', an: ['USA', 'Stany Zjednoczone Ameryki', 'Stany', 'US'], ac: ['Washington', 'Waszyngton DC'] }
    ]
  },

  oceania: {
    label: 'Australia i Oceania',
    rotate: [-160, 20],
    countries: [
      { n: 'Australia', c: 'Canberra', e: 'Australia', ac: ['Kanbera'] },
      { n: 'Fidżi', c: 'Suva', e: 'Fiji' },
      { n: 'Nowa Zelandia', c: 'Wellington', e: 'New Zealand' },
      { n: 'Papua-Nowa Gwinea', c: 'Port Moresby', e: 'Papua New Guinea' },
      { n: 'Mikronezja', c: 'Palikir', e: 'Micronesia', an: ['Sfederowane Stany Mikronezji'] },
      { n: 'Tuvalu', c: 'Vaiaku', e: 'Tuvalu', p: [179.2, -8.5], ac: ['Funafuti'] }
    ]
  },

  azja: {
    label: 'Azja',
    rotate: [-90, -40],
    countries: [
      { n: 'Afganistan', c: 'Kabul', e: 'Afghanistan' },
      { n: 'Arabia Saudyjska', c: 'Rijad', e: 'Saudi Arabia', ac: ['Riyadh', 'Rijad'] },
      { n: 'Armenia', c: 'Erywań', e: 'Armenia', ac: ['Erewan', 'Yerevan'] },
      { n: 'Azerbejdżan', c: 'Baku', e: 'Azerbaijan' },
      { n: 'Bangladesz', c: 'Dhaka', e: 'Bangladesh', ac: ['Dakka', 'Dhakka'] },
      { n: 'Chiny', c: 'Pekin', e: 'China', ac: ['Beijing'] },
      { n: 'Cypr', c: 'Nikozja', e: ['Cyprus', 'N. Cyprus'], ac: ['Nicosia'] },
      { n: 'Filipiny', c: 'Manila', e: 'Philippines' },
      { n: 'Gruzja', c: 'Tbilisi', e: 'Georgia' },
      { n: 'Indie', c: 'Nowe Delhi', e: 'India', ac: ['Delhi', 'New Delhi'] },
      { n: 'Indonezja', c: 'Dżakarta', e: 'Indonesia', ac: ['Jakarta'] },
      { n: 'Irak', c: 'Bagdad', e: 'Iraq' },
      { n: 'Iran', c: 'Teheran', e: 'Iran' },
      { n: 'Izrael', c: 'Jerozolima', e: 'Israel' },
      { n: 'Japonia', c: 'Tokio', e: 'Japan', ac: ['Tokyo'] },
      { n: 'Kazachstan', c: 'Astana', e: 'Kazakhstan' },
      { n: 'Kirgistan', c: 'Biszkek', e: 'Kyrgyzstan', an: ['Kirgizja', 'Kirgizstan'], ac: ['Bishkek'] },
      { n: 'Korea Południowa', c: 'Seul', e: 'South Korea', an: ['Korea Płd'] },
      { n: 'Korea Północna', c: 'Pjongjang', e: 'North Korea', an: ['Korea Płn'], ac: ['Phenian', 'Pyongyang'] },
      { n: 'Kuwejt', c: 'Kuwejt', e: 'Kuwait' },
      { n: 'Liban', c: 'Bejrut', e: 'Lebanon' },
      { n: 'Malezja', c: 'Kuala Lumpur', e: 'Malaysia' },
      { n: 'Mongolia', c: 'Ułan Bator', e: 'Mongolia', ac: ['Ulaanbaatar'] },
      { n: 'Pakistan', c: 'Islamabad', e: 'Pakistan' },
      { n: 'Rosja', c: 'Moskwa', e: 'Russia', an: ['Federacja Rosyjska'] },
      { n: 'Singapur', c: 'Singapur', e: 'Singapore' },
      { n: 'Syria', c: 'Damaszek', e: 'Syria' },
      { n: 'Tadżykistan', c: 'Duszanbe', e: 'Tajikistan', ac: ['Dushanbe', 'Duszambe'] },
      { n: 'Turcja', c: 'Ankara', e: 'Turkey' },
      { n: 'Turkmenistan', c: 'Aszchabad', e: 'Turkmenistan', ac: ['Aszgabat', 'Ashgabat'] },
      { n: 'Uzbekistan', c: 'Taszkent', e: 'Uzbekistan', ac: ['Tashkent'] },
      { n: 'Zjednoczone Emiraty Arabskie', c: 'Abu Zabi', e: 'United Arab Emirates', an: ['ZEA', 'Emiraty', 'Emiraty Arabskie'], ac: ['Abu Dhabi'] }
    ]
  }
};
